### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Foodmux
email: foodmux@gmail.com
description: Amazing food. All the time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://foodmux.in" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: "#efeeff"
twitter_username: foodmux
github_username: goforbg
author: Bharadwaj Giridhar
logo: assets/images/large-logo.png
twitter:
  username: goforbg
social:
  name: Bharadwaj Giridhar
  links:
    - https://twitter.com/goforbg
    - https://www.facebook.com/goforbg
    - https://www.linkedin.com/in/goforbg
    - https://github.com/goforbg

languages: ["en"]
ampdir: amp

github: https://github.com/goforbg/foodmux-website

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
